mutoblog/mutoblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from suns.views import index, SignUpView

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', index, name='main'),
    path('auth/', include('suns.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

mutoblog/suns/urls.py
from django.contrib.auth.views import (LogoutView, LoginView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,)
from django.urls import path
from . import views

app_name = 'suns'
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'),
    path(
        'login/',
        LoginView.as_view(template_name='login.html'),
        name='login'),
    path('profile/<str:username>/', views.profile, name='profile'),
]

mutoblog/suns/models.py
from typing import Any
from django.db import models
from django.contrib.auth.models import AbstractUser


class Mutant(AbstractUser):
    nickname = models.CharField(blank=True, max_length=64)
    avatars = models.ImageField(
        'Картинка солнышка',
        upload_to='mutants/',
        blank=True,
    )

    STATUS_CHOICES = [
        ("activ", "Актив"),
        ("old", "Мутоолдовец"),
        ("intern", "Стажер"),
        ("friend", "Друг команды"),
    ]

    status = models.CharField(choices=STATUS_CHOICES, default="activ", max_length=16)

    def __str__(self):
        if self.nickname:
            return self.nickname
        return self.first_name


class Sun(models.Model):
    name = models.CharField(max_length=32,
                            unique=True,
                            verbose_name="Название солнышка")
    image = models.ImageField(
        'Картинка солнышка',
        upload_to='suns/image',
        blank=True,
        null=True
    )
    description = models.TextField(blank=True, null=True)
    mutant = models.ManyToManyField(Mutant, verbose_name='мутант', blank=True, related_name='suns')

mutoblog/suns/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import Mutant


class MutantCreationForm(UserCreationForm):

    class Meta:
        model = Mutant
        fields = ('email', 'nickname', 'username')


class MutantUserChangeForm(UserChangeForm):

    class Meta:
        model = Mutant
        fields = ("email",)

mutoblog/suns/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .models import Mutant, Sun

from .forms import MutantCreationForm

# Create your views here.
def index(request):
    context = {
        'activ': status_mutant('activ'),
        'old': status_mutant('old'),
        'intern': status_mutant('intern'),
        'friend': status_mutant('friend'),
    }
    template = 'index.html'
    return render(request, template, context)

def status_mutant(status):
    mutants = Mutant.objects.filter(status=status)
    return mutants

class SignUpView(CreateView):
    form_class = MutantCreationForm
    success_url = reverse_lazy("login")
    template_name = "signup.html"

def profile(request, username):
    user = get_object_or_404(Mutant, username=username)
    suns = Sun.objects.filter(mutant=user)

    context = {
        'mutant': user,
        'suns': suns,
    }
    return render(request, 'profile.html', context)

# TODO настроить админку

mutoblog/templates/Index.html
{% include 'base.html' %}


{% block content %}
<div class='mutant-status'> <h4 class="title-status">Актив</h4></div>
  {% for mutant in activ %}
     {% include 'mutant.html' %}
  {% endfor %}
  <div class='mutant-status'> <h4 class="title-status">Стажеры</h4></div>
  {% for mutant in intern %}
     {% include 'mutant.html' %}
  {% endfor %}
  <div class='mutant-status'> <h4 class="title-status">Мутоолдовцы</h4></div>
  {% for mutant in old %}
     {% include 'mutant.html' %}
  {% endfor %}
  <div class='mutant-status'> <h4 class="title-status">Друзья команды</h4></div>
  {% for mutant in friend %}
     {% include 'mutant.html' %}
  {% endfor %}
{% endblock %}

mutoblog/templates/base.html
<!doctype html>
{% load static %}

<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/class.css'%}" type="text/css">
        <meta charset="utf-8">
        <meta name="description" content="Сайт мутантов для назначения солнышек">
        <title>{% block title %}Мутоблок{% endblock %}</title>
        <script src="{% static 'img/bakler.ico' %}"></script>
        <link rel="icon" href="{% static 'img/bakler.ico' %}" type="image">

    </head>
<body>
    <div class='page'>
        <header>
            <a href={% url "main" %}>
            <img src="{% static 'img/header.png' %}">
            <a>
            {% comment %} <div class="menu">
                {% if request.user.is_authenticated%}
                <a href="{% url 'suns:logout' %}">Выйти</a>
                {% else %}
                <a href="{% url 'suns:signup' %}">Регистрация</a>
                <a href="{% url 'suns:login' %}">Войти</a>
                {% endif %}
            </div> {% endcomment %}
        </header>
    </div>
</body>
</html>

mutoblog/templates/login.html
{% extends  'base.html' %}

{% block content %}
<h2>Войти</h2>
<form method="post">
  {% csrf_token %}
  <div class="main">
  {% for field in form %}
  <div class="form-title">
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
    </label>
  </div>
    {{ field }}
    {% comment %} {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %} {% endcomment %}
  {% endfor %}
  <div class="mutant-button">
  <button type="submit">Драться</button>
  <button type="submit">Думать</button>
  </div>
    </div>
</form>
{% endblock %}

mutoblog/templates/mutant.html
{% load thumbnail %}
{% load static %}
<div class="mutant">
    <div class="mutant-image">
        {% thumbnail mutant.avatars "64x64" crop="center" as im %}
        <img src="{{ im.url }}" class="mutant-avatars">
        {% endthumbnail %}
        <p class="mutant-nickname">{{ mutant.nickname }}</p>
        {% comment %} <a href="{% url 'suns:profile' mutant.username %}" class="mutant-nickname">{{ mutant.nickname }}</a> {% endcomment %}
    </div>
    <div class="mutant-sun">
        {% for sun in mutant.suns.all %}
            {% thumbnail sun.image "64x64" crop="center" as im %}
                <img src="{{ im.url }}" class="sun-image" title="{{ sun.description }}">
            {% endthumbnail %}
        {% endfor %}
    </div>

</div>

mutoblog/templates/profile.html


{% include 'base.html' %}
{% block content %}

<p>{{ mutant.nickname }}</p>
{% endblock %}

mutoblog/templates/signup.html
{% include 'base.html' %}
{% block content %}

<h2 class="auth-title">Регистрация</h2>

<form method="post">
  {% csrf_token %}
  <div class="main">
  {% for field in form %}
  <div class="form-title">
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
    </label>
  </div>
    {{ field }}
    {% comment %} {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %} {% endcomment %}
  {% endfor %}
  <div class="mutant-button">
  <button type="submit">Драться</button>
  <button type="submit">Думать</button>
  </div>
    </div>
</form>
{% endblock %}